create database zomato_restaurant;

use  zomato_restaurant;


--                                                                                 Zomato MySQL — 20 Mixed Questions



-- 1.	Display the 5 customers who have placed the highest-value orders, showing customer name and order amount. 

select customers.customer_name , orders.amount as total_amount
from orders
join customers on orders.Customer_ID = customers.Customer_ID
order by orders.amount desc 
limit 5 ;





-- 2.	Find the total revenue generated by each restaurant from delivered orders. Display restaurant name and total revenue. 



select restaurant.restaurant_name , sum(orders.amount) as total_revenue
from restaurant
join orders on restaurant.restaurant_id = orders.restaurant_id
where orders.status = "delivered"
group by restaurant.restaurant_name;


-- 3.	Display all restaurants in Delhi or Mumbai having a rating greater than 4.0, sorted by rating descending. 

SELECT restaurant_name, city, rating
FROM restaurant
WHERE city IN ('Delhi', 'Mumbai')
  AND rating > 4.0
ORDER BY rating DESC;



-- 4.	Find the number of orders placed by each customer and display only customers who have placed at least 2 orders. 

SELECT customers.customer_name,
       COUNT(orders.order_id) AS order_count
FROM customers 
JOIN orders 
  ON customers.customer_id = orders.customer_id
GROUP BY customers.customer_id, customers.customer_name
HAVING COUNT(orders.order_id) >= 2;



-- 5.	Display the top 3 most expensive delivered orders, along with the customer name and restaurant name. 

SELECT orders.order_id,
       customers.customer_name,
       restaurant.restaurant_name,
       orders.amount
FROM orders 
JOIN customers 
  ON orders.customer_id = customers.customer_id
JOIN restaurant
  ON orders.restaurant_id = restaurant.restaurant_id
WHERE orders.status = 'Delivered'
ORDER BY orders.amount DESC
LIMIT 3;



-- 6.	Find the average order amount for each restaurant and display only restaurants whose average order amount is greater than ₹600. 

SELECT restaurant.restaurant_name,
       AVG(orders.amount) AS avg_order_amount
FROM restaurant
JOIN orders 
  ON restaurant.restaurant_id = orders.restaurant_id
GROUP BY restaurant.restaurant_id, restaurant.restaurant_name
HAVING AVG(orders.amount) > 600;





-- 7.	Display customer name, restaurant name, cuisine, order amount, and order status for all orders where the order amount is greater than ₹700. 

SELECT customers.customer_name,
       restaurant.restaurant_name,
       restaurant.cuisine,
       orders.amount,
       orders.status
FROM orders 
JOIN customers 
  ON orders.customer_id = customers.customer_id
JOIN restaurant
  ON orders.restaurant_id = restaurant.restaurant_id
WHERE orders.amount > 700;




-- 8.	Find the total revenue generated by each city, based on the restaurant's city. Display only cities generating more than ₹2,000. 

SELECT restaurant.city,
       SUM(orders.amount) AS total_revenue
FROM restaurant
JOIN orders 
  ON restaurant.restaurant_id = orders.restaurant_id
GROUP BY restaurant.city
HAVING SUM(orders.amount) > 2000;



-- 9.	Display all restaurants sorted by rating from highest to lowest. Skip the first 2 restaurants and display the next 4. 

SELECT restaurant_name, rating
FROM restaurant
ORDER BY rating DESC
LIMIT 4 OFFSET 2;




-- 10.	Find the number of delivered and cancelled orders for each restaurant. Display restaurant name, status, and order count. 

SELECT restaurant.restaurant_name,
       orders.status,
       COUNT(orders.order_id) AS order_count
FROM restaurant
JOIN orders 
  ON restaurant.restaurant_id = orders.restaurant_id
WHERE orders.status IN ('Delivered', 'Cancelled')
GROUP BY restaurant.restaurant_name, orders.status
order by orders.status desc;




-- 11.	Find the restaurant with the highest total delivered revenue. 

SELECT restaurant.restaurant_name,
       SUM(orders.amount) AS total_revenue
FROM restaurant
JOIN orders 
  ON restaurant.restaurant_id = orders.restaurant_id
WHERE orders.status = 'Delivered'
GROUP BY restaurant.restaurant_id, restaurant.restaurant_name
ORDER BY total_revenue DESC
LIMIT 1;



-- 12.	Find customers whose average order amount is greater than ₹600. Display customer name and average order amount. 


SELECT customers.customer_name, customers.customer_id,
       AVG(orders.amount) AS avg_order_amount
FROM customers 
JOIN orders 
  ON customers.customer_id = orders.customer_id
GROUP BY customers.customer_id, customers.customer_name
HAVING AVG(orders.amount) > 600;



-- 13.	Display the second and third highest-rated restaurants using ORDER BY, LIMIT, and OFFSET. 

select restaurant_name , rating 
from restaurant
order by rating desc
limit 2 offset 1 ;


-- 14.	Find the average review rating for each restaurant. Display only restaurants having an average review rating of 4 or higher, sorted from highest to lowest. 

select restaurant.restaurant_name , avg(review.rating) as avg_review_rating
from restaurant 
join review on restaurant.restaurant_id = review.restaurant_id
group by restaurant.restaurant_name
having avg(review.rating) >=4
order by avg(review.rating) desc ;



-- 15.	Display customer name, restaurant name, review rating, and review text for all reviews where the rating is 5. 


select customers.customer_name , 
restaurant.restaurant_name , 
review.rating , 
review.review_text
from customers
join review on customers.Customer_ID = review.customer_id
join restaurant on review.restaurant_id = restaurant.restaurant_id 
where review.rating = 5;


-- 16.	Find the top 3 customers based on total amount spent on delivered orders. Display customer name and total spending. 

SELECT 
       customers.customer_name,
       SUM(orders.amount) AS total_spending
FROM customers 
JOIN orders 
  ON customers.customer_id = orders.customer_id
WHERE orders.status = 'Delivered'
GROUP BY customers.customer_id, customers.customer_name
ORDER BY total_spending DESC
limit 3 ;
 




-- 17.	Find the number of customers in each city and display only cities having more than 1 customer. 

SELECT city,
       COUNT(customer_id) AS customer_count
FROM customers
GROUP BY city
HAVING COUNT(customer_id) > 1;




-- 18.	Display restaurant name, cuisine, number of orders, and total order amount for each restaurant. Include only restaurants having at least 2 orders, and sort by total order amount descending. 

select restaurant.restaurant_name , 
restaurant.cuisine ,
 count(orders.order_id) as total_order ,
 sum(orders.amount) as total_order_amount
 from restaurant 
 join orders on restaurant.restaurant_id = orders.restaurant_id
 group by restaurant.restaurant_name ,  restaurant.cuisine 
 having total_order >= 2
 order by total_order_amount ;



-- 19.	Find the restaurant that has received the highest number of 5-star reviews. Display restaurant name and number of 5-star reviews.


SELECT restaurant.restaurant_name, 
       COUNT(review.review_id) AS five_star_reviews
FROM restaurant
JOIN review
  ON restaurant.restaurant_id = review.restaurant_id
WHERE review.rating = 5
GROUP BY  restaurant.restaurant_name
ORDER BY five_star_reviews DESC
LIMIT 5;



select count(review_id)  , rating
from review
group by rating;


